# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target ‘FOSinOC’ do
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'AFNetworking', '~> 3.0'
pod 'SSKeychain'
pod 'SDWebImage', '~>3.8'
end

target 'FOSinOC' do

end

target 'FOSinOC' do

end

