# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'FoodOrderingSystem' do
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'Alamofire', '~> 3.0'
pod 'KeychainAccess'
end

target 'FoodOrderingSystemTests' do

end

target 'FoodOrderingSystemUITests' do

end

